### PR TITLE
feat(fixtures): allow formatting fixtures results

### PR DESCRIPTION
**Pull request by andrefgneves**
**What**: This will pass the result of each fixture through the passed `formatResult`.

**Why**: Parity with tests passed directly

**How**: Just run the resulting code of each fixture through the formatter function.

### CODE REVIEW

**Comment by kentcdodds** [comment]
We already have `formatResult`: https://github.com/babel-utils/babel-plugin-tester#formatresult

I'm not sure I understand why formatting a fixture is at all relevant because you're in control of the fixture anyway. Just supply it in the format you want 🤷‍♂️

**Comment by andrefgneves** [comment]
IMHO, when used with `snapshot` this becomes useful in order to make the fixtures output more readable. It can also make it easier to spot differences when jest displays the expected/received error. 

I'm currently running my fixture's output through `prettier`:

```js
formatResult: code => prettier.format(code, { parser: 'babel' }),
```

I see `formatResult` almost as a jest snapshot serializer.

**Comment by kentcdodds** [comment]
> this becomes useful in order to make the fixtures output more readable

Hmmm.... Fixture output? But fixtures are input. And YOU are responsible for input. Can't you format it when you make it? It's not generated...

**Comment by kentcdodds** [comment]
Ok, I think I was confused by wording. So now I understand your want to format the resulting output of a fixture, not the input.

I thought this was already supported, but I guess it's not? Hmmm.

**Comment by kentcdodds** [comment]
Ok, yeah. I totally misunderstood this one. Thanks for the contribution

**Comment by kentcdodds** [comment]
Thank you!

**Comment by andrefgneves** [comment]
No worries. Thanks for merging 👍

**Pull request merged**
