### PR TITLE
Feat: adds jsx support

### PR DESCRIPTION
**Pull request by lifeart**
**What**: Added support for .jsx files in fixtures

**Why**: Babel plugin can manage .jsx

**How**: Some code changes

### CODE REVIEW

**Comment by lifeart** [comment]
@kentcdodds done

**Comment by kentcdodds** [comment]
Looks like there's a failing test

**Comment by kentcdodds** [comment]
Looks like there's a failing test

**Comment by lifeart** [comment]
yes, but, looks like it's kinda ast version mismatch or kinda, can't figure out "broken part" is master green?

**Comment by kentcdodds** [comment]
Yes. Matter is green.

**Comment by lifeart** [comment]
adding `.babelrc` into fixtures folder failing this tests, don't think it make sence. Going to rewrite assert logic.

**Comment by lifeart** [comment]
changing names from `jsx-support` to `jsx support` fixes this issue, looks like it's an jest assert bug.

**Comment by kentcdodds** [comment]
@all-contributors please add @lifeart for code and tests

**Comment by kentcdodds** [comment]
@all-contributors please add @lifeart for code and tests

**Comment by kentcdodds** [comment]
@all-contributors please add @lifeart for code and tests

**Comment by kentcdodds** [comment]
Sorry about all those comments, I didn't realize that I hadn't gotten the bot setup on this project yet. Thanks so much for your help!

**Pull request merged**
